name: Build & Deploy Spring App

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 23
              uses: actions/setup-java@v3
              with:
                java-version: '23'
                distribution: 'corretto'

            - name: Unit Tests
              run: mvn -B test --file pom.xml

            - name: Build Spring Boot App
              run: |
                mvn clean
                mvn -B package --file pom.xml

            - name: Build Docker Image
              uses: actions/build-push-action@v2
              with:
                context: .
                dockerfile: Dockerfile
                push: false
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Push Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}