name: Build & Deploy Spring App

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 23
              uses: actions/setup-java@v3
              with:
                java-version: '23'
                distribution: 'corretto'

            - name: Unit Tests
              run: mvn -B test --file pom.xml

            - name: Build Spring Boot App
              run: |
                mvn clean
                mvn -B package --file pom.xml